
spring:
  application:
    name: visrater-backend
  servlet:
    multipart:
      enabled: true
      location: /tmp
server:
  port: 9000
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
graphql:
  servlet:
    actuator-metrics: true
    corsEnabled: true
  playground:
    cdn:
      version: latest
altair:
  enabled: false
  cdn:
    enabled: true
graphiql:
  enabled: true
  cdn:
    enabled: true
    version: 0.17.5
voyager:
  enabled: false
  cdn:
    enabled: true
graphql.playground:
  enabled: false
  cdn:
    enabled: true
logging:
  level:
    root: ERROR
    org.spingframework.web: ERROR
    com.hawazin.visrater: DEBUG
spotify:
  client:
    id: 793c68b38b06461d8127f90148edc66a
    secret: {f245c4d9b1ad42399f98e922c91d02ea:default}
  accounts: 'https://accounts.spotify.com'
  api: 'https://api.spotify.com/v1'
